language: cpp
compiler: gcc
dist: trusty

before_install:
# C++17
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
# C++17
- sudo apt-get install -qq g++-7
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90

#before_script:
#- sudo apt-get install libboost-test-dev -y

script:
- cmake .
- cmake --build .
#- cmake --build . --target test
#- cmake --build . --target package

#deploy:
#  provider: script
#  skip_cleanup: true
#  script:
#  - curl -T editor-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -u artbataev:$BINTRAY_API_KEY "https://api.bintray.com/content/artbataev1/Otus_Assignments/Otus_Cpp_5/$TRAVIS_BUILD_NUMBER/editor-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;publish=1"
#  on:
#    branch: master